name: Run Tests movie model


on :
  push:
      paths:
        - 'docker_volume/unittest/kpi_movie_model/dict_prediction_comparaison.pkl'
        - 'docker_volume/unittest/kpi_movie_model/dict_stability.pkl'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest numpy pandas
    - name: Run tests model
      run: |
        cd test_unitaires
        pytest movie_model_test.py